### ISSUE TITLE
AttributeError: 'SafeTransport' object has no attribute 'context'

### ISSUE THREAD

**Issue by vimalloc** [joshmarshall/jsonrpclib#34]
I'm running into an error when running this code on python 2.7.9
```python
import jsonrpclib
server = jsonrpclib.Server('https://<ip_addr>:<port>')
print server.foo()
```
And get the following stacktrace:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lgbland/code/xmsso/venv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 274, in __call__
    return self.__send(self.__name, args)
  File "/home/lgbland/code/xmsso/venv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 224, in _request
    response = self._run_request(request)
  File "/home/lgbland/code/xmsso/venv/lib/python2.7/site-packages/jsonrpclib/jsonrpc.py", line 242, in _run_request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1293, in single_request
    h = self.make_connection(host)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1509, in make_connection
    self._connection = host, HTTPS(chost, None, context=self.context, **(x509 or {}))
AttributeError: 'SafeTransport' object has no attribute 'context'
```

The same code works fine in python 2.7.6. Some underlying change in xmlrpclib perhaps?

**Comment by cappy123abc** [comment]
I've got he same problem.

**Comment by cappy123abc** [comment]
Release notes for 2.7.9

+++++++++++
Python News
+++++++++++

What's New in Python 2.7.9?
===========================

*Release date: 2014-12-10*

Library
-------

- Issue #22959: Remove the *check_hostname* parameter of
  httplib.HTTPSConnection. The *context* parameter should be used instead.

- Issue #16043: Add a default limit for the amount of data xmlrpclib.gzip_decode
  will return. This resolves CVE-2013-1753.

- Issue #16042: CVE-2013-1752: smtplib: Limit amount of data read by limiting
  the call to readline().  Original patch by Christian Heimes.

- Issue #16041: In poplib, limit maximum line length read from the server to
  prevent CVE-2013-1752.

- Issue #22960: Add a context argument to xmlrpclib.ServerProxy.

**Comment by msabramo** [comment]
It looks like this issue was fixed by https://github.com/joshmarshall/jsonrpclib/pull/36 and the fix is present in [jsonrpclib 0.1.7 on PyPI](https://pypi.python.org/pypi/jsonrpclib/0.1.7).

I think this issue can be closed.
